language: node_js

node_js:
  - "10"
  - "12"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g gulp-cli

install:
  - npm install
  - gulp run-codegen

script:
  - npm run pretest
  - npm run test:nyc
  - PHP_PARSER_VERSION=7_3 npm run test:nyc:combine
  - PHP_PARSER_VERSION=7_2 npm run test:nyc:combine
  - PHP_PARSER_VERSION=7_1 npm run test:nyc:combine
  - PHP_PARSER_VERSION=7_0 npm run test:nyc:combine

after_success: npm run test:coveralls
