language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g gulp-cli

install:
  - npm install
  - gulp run-codegen

script:
  - npm test

after_success: npm run test:coverage
