language: node_js

node_js:
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g gulp-cli

install:
  - npm install
  - gulp copy-json

script:
  - npm test
